# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [1]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [5]:
lista = [1, 2, 3, 4, 5]

np_list = np.asarray(lista)
print(np_list)

[1 2 3 4 5]


Ejercicio 3: Suma los siguientes dos arrays

In [6]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

np_sum_array = a + b
print(np_sum_array)

[[11 13 15]
 [17 19 21]]


Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [7]:
a = np.array([[4,2,2],
              [4,1,0]])

np_scalar_multilication = a * 3.2
print(np_scalar_multilication)

[[12.8  6.4  6.4]
 [12.8  3.2  0. ]]


Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [15]:
a = np.array([x for x in range(9)])
print(a)
print(np.shape(a))

np_reshaped = a.reshape([3, 3])
print(np_reshaped)
print(np_reshaped.shape)

[0 1 2 3 4 5 6 7 8]
(9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [16]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

np_format_type = a.astype(int)
print(np_format_type)
print(np_format_type.dtype)

[[2 3 1]
 [4 2 1]]
int64


Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [17]:
np_eye = np.eye(5)
print(np_eye)

np_boolseye = np_eye.astype(bool)
print(np_boolseye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [19]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

np_concatenated = np.concatenate([a1, a2], axis = 1)
print(np_concatenated)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Ejercicio 9: Cocatena de forma vertical los mismos array

In [20]:
np_concatenated = np.concatenate([a1, a2], axis = 0)
print(np_concatenated)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [22]:
np_skipping_arrange = np.arange(0, 101, 2)
print(np_skipping_arrange)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [24]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

np_bigger_array = np.where(a > b)
print(np_bigger_array)

# Alternative returning a list containing the comparison element-wise
np_bigger_array = a > b
print(np_bigger_array)

[False False  True False  True]
(array([2, 4]),)


Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [25]:
np_skipping_arrange = np.arange(0, 101, 5)
print(np_skipping_arrange)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [27]:
np_23_matrix = 23 * np.ones([2, 3])
print(np_23_matrix)

np_23_matrix_bis = np.full([2, 3], 23)
print(np_23_matrix_bis)

[[23. 23. 23.]
 [23. 23. 23.]]
[[23 23 23]
 [23 23 23]]


Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [28]:
np_rand_normal = np.random.normal(size = [8, 2])
print(np_rand_normal)

[[ 0.73211479  0.26108612]
 [ 0.27155054  1.77985884]
 [ 0.67492147 -0.17606363]
 [ 0.90102182  0.53840829]
 [ 1.03939893  0.20364849]
 [-1.061821   -0.680477  ]
 [-1.28310165  0.64583484]
 [ 0.7516759   0.85333896]]


Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [29]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

np_matrix_multiplication = np.matmul(a, b)
print(np_matrix_multiplication)

np_matrix_multiplication_elementwise = a * b
print(np_matrix_multiplication_elementwise)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]
[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [30]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

np_sorted_indexes = np.argsort(a)
print(a[np_sorted_indexes])
print(a[np_sorted_indexes][::-1])

[   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]
[1101  939  923  387  299  292  199   91   82   38    2    2    1    0]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [40]:
np_read = arr = np.loadtxt("./datasets/venta_libros.csv", delimiter=",", encoding="utf-8-sig")
print(np_read)
print(np_read.shape)

year = np_read[:, 0].astype(int)
month = np_read[:, 1].astype(int)
books = np_read[:, 2].astype(int)

print(year)
print(month)
print(books)

[[2.019e+03 1.000e+00 1.060e+02]
 [2.019e+03 2.000e+00 4.000e+02]
 [2.019e+03 3.000e+00 3.390e+02]
 [2.019e+03 4.000e+00 3.890e+02]
 [2.019e+03 5.000e+00 1.410e+02]
 [2.019e+03 6.000e+00 3.320e+02]
 [2.019e+03 7.000e+00 3.860e+02]
 [2.019e+03 8.000e+00 3.070e+02]
 [2.019e+03 9.000e+00 3.040e+02]
 [2.019e+03 1.000e+01 1.670e+02]
 [2.019e+03 1.100e+01 1.330e+02]
 [2.019e+03 1.200e+01 1.510e+02]
 [2.020e+03 1.000e+00 2.760e+02]
 [2.020e+03 2.000e+00 5.700e+01]
 [2.020e+03 3.000e+00 1.250e+02]
 [2.020e+03 4.000e+00 2.700e+01]
 [2.020e+03 5.000e+00 2.220e+02]
 [2.020e+03 6.000e+00 3.630e+02]
 [2.020e+03 7.000e+00 2.600e+01]
 [2.020e+03 8.000e+00 1.620e+02]
 [2.020e+03 9.000e+00 3.830e+02]
 [2.020e+03 1.000e+01 3.830e+02]
 [2.020e+03 1.100e+01 1.790e+02]
 [2.020e+03 1.200e+01 3.860e+02]
 [2.021e+03 1.000e+00 4.320e+02]
 [2.021e+03 2.000e+00 4.820e+02]
 [2.021e+03 3.000e+00 2.020e+02]
 [2.021e+03 4.000e+00 1.150e+02]
 [2.021e+03 5.000e+00 4.200e+02]
 [2.021e+03 6.000e+00 8.700e+01]
 [2.021e+0

Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [41]:
print(f"Mayor cantidad de libros: {np.max(books)} en el índice {np.argmax(books)}")
print(f"Corresponde al mes {month[np.argmax(books)]} de {year[np.argmax(books)]}")

Mayor cantidad de libros: 489 en el índice 31
Corresponde al mes 8 de 2021


Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [51]:
print(f"Ventas totales {np.sum(books)}")
print(f"Ventas promedio {np.mean(books):,.2f}")
print(f"Mediana de ventas {np.median(books)}")
print(f"Desviación estandar de las ventas {np.std(books):,.2f}")

Ventas totales 12542
Ventas promedio 261.29
Mediana de ventas 267.0
Desviación estandar de las ventas 136.61
